name: GetSukiSUManager

permissions:
  contents: write
  actions: read

on:
  workflow_dispatch:
    inputs:
      kernelsu_variant:
        required: true
        type: string
        default: "SukiSU"

jobs:
  get_sukisu_manager:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: 安装依赖
        run: sudo apt update && sudo apt install -y git curl jq unzip

      - name: 检查输入参数
        run: |
          if [ "${{ inputs.kernelsu_variant }}" != "SukiSU" ]; then
            echo "仅支持 SukiSU 变体"
            exit 1
          fi

      - name: 克隆 SukiSU 仓库并获取版本号
        run: |
          git clone https://github.com/SukiSU-Ultra/SukiSU-Ultra.git
          cd SukiSU-Ultra
          GIT_COUNT=$(git rev-list --count HEAD)
          KSU_VERSION=$((10000 + GIT_COUNT + 606))
          echo "KSU_VERSION=$KSU_VERSION" >> $GITHUB_ENV

      - name: 获取 SukiSU 最新构建的 manager artifact
        run: |
          REPO="SukiSU-Ultra/SukiSU-Ultra"
          echo "获取最新成功的 workflow run ID..."

          RUN_ID=$(curl -s -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/repos/$REPO/actions/workflows/build-manager.yml/runs?status=success" | \
            jq -r '.workflow_runs[0].id')

          if [ -z "$RUN_ID" ] || [ "$RUN_ID" == "null" ]; then
            echo "未找到成功的构建"
            exit 1
          fi

          echo "成功获取 RUN_ID: $RUN_ID"

          echo "获取 artifact 下载链接..."
          ARTIFACTS=$(curl -s -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/artifacts")

          DOWNLOAD_URL=$(echo "$ARTIFACTS" | jq -r '.artifacts[] | select(.name == "manager") | .archive_download_url')

          if [ -z "$DOWNLOAD_URL" ] || [ "$DOWNLOAD_URL" == "null" ]; then
            echo "未找到 manager artifact"
            exit 1
          fi

          echo "正在下载 artifact..."
          curl -L -H "Authorization: token $GH_TOKEN" -o "SukiSU-Manager-${{ env.KSU_VERSION }}.zip" "$DOWNLOAD_URL"

          unzip "SukiSU-Manager-${{ env.KSU_VERSION }}.zip" -d manager

          echo "已解压内容如下："
          ls -lh manager

      - name: 上传 manager APK
        uses: actions/upload-artifact@v4
        with:
          name: SukiSU-Manager-${{ env.KSU_VERSION }}
          path: manager/*.apk
