name: MainKernelBuild

on:
  workflow_dispatch:

jobs:
  download_sukisu_manager:
    name: 下载并上传 SukiSU 管理器
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO: ${{ github.repository }}

    steps:
      - name: 安装依赖
        run: sudo apt update && sudo apt install -y curl jq unzip

      - name: 获取 GetSukiSUManager 最近一次成功构建的 ID
        id: get_run
        run: |
          WORKFLOW_FILE="GetSukiSUManager.yml"

          echo "查询工作流运行 ID..."
          RUNS_JSON=$(curl -s -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/repos/$REPO/actions/workflows/$WORKFLOW_FILE/runs?status=success")

          RUN_ID=$(echo "$RUNS_JSON" | jq -r '.workflow_runs[0].id')

          if [ -z "$RUN_ID" ] || [ "$RUN_ID" == "null" ]; then
            echo "未找到成功运行的 $WORKFLOW_FILE 工作流"
            exit 1
          fi

          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: 获取对应 Artifact 的下载地址
        id: get_artifact
        run: |
          RUN_ID=${{ steps.get_run.outputs.run_id }}

          echo "查询 Run ID = $RUN_ID 的 artifact..."

          ARTIFACTS=$(curl -s -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/artifacts")

          DL_URL=$(echo "$ARTIFACTS" | jq -r '.artifacts[] | select(.name | startswith("SukiSU-Manager")) | .archive_download_url')

          if [ -z "$DL_URL" ] || [ "$DL_URL" == "null" ]; then
            echo "未找到 SukiSU 管理器 Artifact"
            exit 1
          fi

          echo "download_url=$DL_URL" >> $GITHUB_OUTPUT

      - name: 下载并解压管理器 APK
        run: |
          DL_URL="${{ steps.get_artifact.outputs.download_url }}"
          curl -L -H "Authorization: token $GH_TOKEN" -o sukisu-manager.zip "$DL_URL"

          echo "下载完成，开始解压..."
          unzip sukisu-manager.zip -d sukisu-manager

          echo "以下是解压后的文件："
          ls -l sukisu-manager

      - name: 上传解压后的 APK
        uses: actions/upload-artifact@v4
        with:
          name: SukiSU-Manager-From-Main
          path: sukisu-manager/*.apk
